easy_admin:
  entities:
    Users:
      class: App\Entity\Users
      list:
        fields:
          - id
          - email
          - role
          - password
      form:
        fields:
          - email
          - password
          - role
  design:
    brand_color: "#5c6bc0"

  resource: '@EasyCorp\Bundle\EasyAdminBundle\Controller\AdminController'
  prefix: /admin
