<?php

namespace ContainerQSzXFoc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeezerControllershowArtistAlbumsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oK9Iezx.App\Controller\DeezerController::showArtistAlbums()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oK9Iezx.App\\Controller\\DeezerController::showArtistAlbums()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'deezerService' => ['privates', 'App\\Service\\DeezerService', 'getDeezerServiceService', true],
        ], [
            'deezerService' => 'App\\Service\\DeezerService',
        ]))->withContext('App\\Controller\\DeezerController::showArtistAlbums()', $container);
    }
}
