<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQSzXFoc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQSzXFoc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQSzXFoc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQSzXFoc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQSzXFoc\App_KernelDevDebugContainer([
    'container.build_hash' => 'QSzXFoc',
    'container.build_id' => '1de49414',
    'container.build_time' => 1739882382,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQSzXFoc');
