<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJuE3kxe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJuE3kxe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJuE3kxe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJuE3kxe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJuE3kxe\App_KernelDevDebugContainer([
    'container.build_hash' => 'JuE3kxe',
    'container.build_id' => 'b4f36905',
    'container.build_time' => 1739868529,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJuE3kxe');
