<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'deezer_artist_albums' => [['artistId'], ['_controller' => 'App\\Controller\\DeezerController::showArtistAlbums'], [], [['variable', '/', '[^/]++', 'artistId', true], ['text', '/deezer/artist']], [], [], []],
    'app_home_index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'spotify' => [[], ['_controller' => 'App\\Controller\\SpotifyController::index'], [], [['text', '/spotify']], [], [], []],
    'App\Controller\DeezerController::showArtistAlbums' => [['artistId'], ['_controller' => 'App\\Controller\\DeezerController::showArtistAlbums'], [], [['variable', '/', '[^/]++', 'artistId', true], ['text', '/deezer/artist']], [], [], []],
    'App\Controller\HomeController::index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\SpotifyController::index' => [[], ['_controller' => 'App\\Controller\\SpotifyController::index'], [], [['text', '/spotify']], [], [], []],
];
